disabled_rules:
  - nesting
opt_in_rules: # Find all the available rules by running: `swiftlint rules`
  - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
force_cast: warning
force_try:
  severity: warning
line_length: 150
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - url
    - hex
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)

